### ISSUE TITLE
[Feature] Missing the green library badge in modmenu

### ISSUE THREAD

**Issue by nco2k** [SuperMartijn642/Formations#1]
can you please modify the mod so that it gets properly recognized as a library by modmenu, and therefor doesnt show up by default?

apis like fabric, cloth, yacl etc. have a green library badge in modmenu, and only show up if you toggle the button from "Libraries: Hidden" to "Libraries: Shown". i would appreciate it if your library behaved the same.

ps: any plans for formations end? :D

**Comment by SuperMartijn642** [comment]
I added the custom library marker for ModMenu now in version 1.0.0a.

> ps: any plans for formations end? :D

Yes, no clue when though
