### ISSUE TITLE
[Bug] ...1.20.1 Forge 43.3.0

### ISSUE THREAD

**Issue by Krimatoria** [SuperMartijn642/Formations#11]
**Version Info**
- Minecraft, 1.20.1 43.3.0
- Formations 1.0.2a

**What mod loader are you using?**: Forge

**Description of the Bug**
... Crash the game on the latest version, what else can I say here. It just won't start.

### It's in a big build

> [18:11:15] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: formations, class com.supermartijn642.formations.Formations
> java.lang.NoSuchFieldError: STRUCTURE_TYPE
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23703!/:?] {re:classloading}
> 	at com.supermartijn642.formations.Formations.<init>(Formations.java:25) ~[formations-1.0.2a-forge-mc1.20.2.jar%23703!/:?] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23966!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23965!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

> -- Head --
> Thread: Render thread
> Suspected Mods: 
> 	Drippy Loading Screen (drippyloadingscreen), Version: 3.0.1
> 		Mixin class: de.keksuccino.drippyloadingscreen.mixin.mixins.forge.client.MixinForgeLoadingOverlay
> 		Target: net.minecraftforge.client.loading.ForgeLoadingOverlay
> 		at TRANSFORMER/forge@47.3.0/net.minecraftforge.client.loading.ForgeLoadingOverlay.handler$fkn000$drippyloadingscreen$cancelForgeCustomLoadingOverlayRenderingDrippy(ForgeLoadingOverlay.java:1027)
> 
> 	Formations (formations), Version: 1.0.2+a
> 		Issue tracker URL: https://github.com/SuperMartijn642/Formations/issues
> 		at TRANSFORMER/formations@1.0.2+a/com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22)
> Stacktrace:
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23703!/:?] {re:classloading}
> -- MOD formations --
> Details:
> 	Mod File: /C:/Users/Dotka/AppData/Roaming/PrismLauncher/instances/---/.minecraft/mods/formations-1.0.2a-forge-mc1.20.2.jar
> 	Failure message: Formations (formations) has failed to load correctly
> 		java.lang.NoSuchFieldError: STRUCTURE_TYPE
> 	Mod Version: 1.0.2+a
> 	Mod Issue URL: https://github.com/SuperMartijn642/Formations/issues
> 	Exception message: java.lang.NoSuchFieldError: STRUCTURE_TYPE
> Stacktrace:
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23703!/:?] {re:classloading}
> 	at com.supermartijn642.formations.Formations.<init>(Formations.java:25) ~[formations-1.0.2a-forge-mc1.20.2.jar%23703!/:?] {re:classloading,re:mixin}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23966!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23965!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

### Here's a new one, only your mod doesn't cost anything anymore.

> [21:48:55] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: formations, class com.supermartijn642.formations.Formations
> java.lang.NoSuchFieldError: STRUCTURE_TYPE
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23129!/:?] {re:classloading}
> 	at com.supermartijn642.formations.Formations.<init>(Formations.java:25) ~[formations-1.0.2a-forge-mc1.20.2.jar%23129!/:?] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23132!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23131!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
> [21:48:55] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.3.0, for MC 1.20.1 with MCP 20230612.114412
> [21:48:55] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.3.0 Initialized
> [21:48:56] [Render thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$ColorResolvers to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterItemDecorationsEvent to a broken mod state
> [21:48:56] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterPresetEditorsEvent to a broken mod state
> [21:48:56] [Render thread/INFO] [minecraft/ReloadableResourceManager]: Reloading ResourceManager: vanilla
> [21:48:57] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
> [21:48:57] [Worker-Main-2/INFO] [minecraft/UnihexProvider]: Found unifont_all_no_pua-15.0.06.hex, loading
> [21:48:58] [Worker-Main-7/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
> [21:48:59] [Worker-Main-7/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$ModifyBakingResult to a broken mod state
> [21:48:59] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: minecraft:item.goat_horn.play
> [21:48:59] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
> [21:48:59] [Render thread/INFO] [mojang/Library]: OpenAL initialized on device OpenAL Soft on HP X24ih (NVIDIA High Definition Audio)
> [21:48:59] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:48:59] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
> [21:49:00] [Render thread/WARN] [minecraft/ShaderInstance]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
> [21:49:00] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:49:00] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> [21:49:00] [Render thread/INFO] [minecraft/TextureAtlas]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
> [21:49:00] [Render thread/ERROR] [ne.mi.fm.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
> Negative index in crash report handler (33/35)
> [21:49:00] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 1fc46a8a-280f-486a-98bc-79414c65d5d9
> [21:49:00] [Render thread/FATAL] [ne.mi.cl.lo.ClientModLoader/]: Crash report saved to C:\Users\Dotka\AppData\Roaming\PrismLauncher\instances\1.20.1(1)\.minecraft\crash-reports\crash-2024-08-20_21.49.00-fml.txt
> [21:49:00] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ba2c3aeb-670a-4e40-bff4-9a8ec9017bf6
> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 2024-08-20 21:49:00
> Description: Mod loading error has occurred
> 
> java.lang.Exception: Mod Loading has failed
> 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.0-universal.jar%23135!/:?] {re:classloading}
> 	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.0-universal.jar%23135!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading}
> 	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.0-universal.jar%23135!/:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23130!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Suspected Mod: 
> 	Formations (formations), Version: 1.0.2+a
> 		Issue tracker URL: https://github.com/SuperMartijn642/Formations/issues
> 		at TRANSFORMER/formations@1.0.2+a/com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22)
> Stacktrace:
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23129!/:?] {re:classloading}
> -- MOD formations --
> Details:
> 	Mod File: /C:/Users/Dotka/AppData/Roaming/PrismLauncher/instances/1.20.1(1)/.minecraft/mods/formations-1.0.2a-forge-mc1.20.2.jar
> 	Failure message: Formations (formations) has failed to load correctly
> 		java.lang.NoSuchFieldError: STRUCTURE_TYPE
> 	Mod Version: 1.0.2+a
> 	Mod Issue URL: https://github.com/SuperMartijn642/Formations/issues
> 	Exception message: java.lang.NoSuchFieldError: STRUCTURE_TYPE
> Stacktrace:
> 	at com.supermartijn642.formations.FormationsStructures.<clinit>(FormationsStructures.java:22) ~[formations-1.0.2a-forge-mc1.20.2.jar%23129!/:?] {re:classloading}
> 	at com.supermartijn642.formations.Formations.<init>(Formations.java:25) ~[formations-1.0.2a-forge-mc1.20.2.jar%23129!/:?] {re:classloading}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23132!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23131!/:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	
**Steps to Reproduce**
...Install the latest version the game will not start. It's simple)

**Screenshots**
![image](https://github.com/user-attachments/assets/14612208-b66d-4adc-9f9d-237c822861d9)

**Comment by wendall911** [comment]
Also crashes on later versions up through 47.3.6

**Comment by SuperMartijn642** [comment]
Please fill in the template

**Comment by Krimatoria** [comment]
> Please fill in the template

Done

**Comment by SuperMartijn642** [comment]
Not entirely sure what happened, it seems the jar did not get reobfuscated when building the mod. My guess is that I switch from a branch for a newer Minecraft version, where obfuscation is no longer necessary, to forge-1.20 and Gradle didn't reload properly.

Anyways, simply building the mod again seems to have fixed it.
I've reuploaded the file to CurseForge and Modrinth, so simply redownloading it should fix the issue.
Thank you for reporting the issue!
