### ISSUE TITLE
[Bug] whats this ass icon ? got nothing to do with the mod :sob:

### ISSUE THREAD

**Issue by VaporeonScripts** [SuperMartijn642/Formations#14]
neoforge 1.21.1 .79
![image](https://github.com/user-attachments/assets/3f7ec0e4-7be4-4338-abc4-b53b9717c3ba)

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/9fff7418-5317-43f4-b5d2-bef26be9faa1)
should be this

**Comment by Leclowndu93150** [comment]
It's the icon of his wireless chargers mod.

**Comment by VaporeonScripts** [comment]
correct, but this is NOT wireless charger mod :sob:

**Comment by Leclowndu93150** [comment]
Ok but calling it ASS is not nice

**Comment by SuperMartijn642** [comment]
I already fixed this a couple months ago, however it seems I didn't have 1.21.1 marked for the upload tasks and thus the file was only marked for 1.21 on Modrinth and CurseForge. I have now marked it for 1.21.1 as well.

Thank you reporting the issue, although I would appreciate it if you filled in the template and used some nicer wording 🙃

**Comment by VaporeonScripts** [comment]
my bad,xd
