### ISSUE TITLE
[Crash] possible server crash due to formations?

### ISSUE THREAD

**Issue by VaporeonScripts** [SuperMartijn642/Formations#15]
neoforge 1.21.1 .83
latest formations mods and library
https://mclo.gs/q5414nv
neoforge support said formations could be the cause

**Comment by SuperMartijn642** [comment]
Does the issue go away if you disable Formations?

**Comment by VaporeonScripts** [comment]
will test that right now

**Comment by VaporeonScripts** [comment]
as of now, seems to work fine without formations, ill test further

**Comment by VaporeonScripts** [comment]
still crashes without it, so its not faulty ig?
