### ISSUE TITLE
[Question] ... Formations mods for Neoforge for Minecraft 1.20.4

### ISSUE THREAD

**Issue by krjencik** [SuperMartijn642/Formations#7]
**Question**
...
When I have these 3 mods (Formations lib, Formations Overworld and Formations Nether) installed only "Formations" show up in mods tab in game - are the other two mods hidden under this title?

**Comment by SuperMartijn642** [comment]
It seems to just show all three mods for me:
![image](https://github.com/SuperMartijn642/Formations/assets/12382965/5352a3f9-a0a3-4f39-a8b1-a323f2aad2a6)
